### ISSUE TITLE
the article title is shown twice

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#16]
Just keep the one on the left, outside the white box.
![image](https://user-images.githubusercontent.com/50109671/103994472-5a30ef00-5197-11eb-88bb-8e93a40b73bb.png)

**Comment by heyarviind** [comment]
this is because Hugo has a site param that is .Title, which shows the title of the current page... so on the left side I get the title from the .Title param but on the right side (in the article itself) there is a heading with the same title...

To fix this we need to remove the heading from all our markdowns... if it doesn't sound good then I have to write a script that will automatically remove the H1 tag from the title but I think this is not the best solution for this

**Comment by andreantonacci** [comment]
Clear, thanks. I'll remove the headings from the MD file, no need to write a script for that. You can move on the other critical issues.

**Comment by heyarviind** [comment]
you can close this issue

**Comment by andreantonacci** [comment]
I'll remove you but I'll keep it open to remember myself of this task

**Comment by andreantonacci** [comment]
Fixed with [5d7d77](https://github.com/tilburgsciencehub/tsh-website/commit/5d7d77ef5417f7dbab6ea020f3d04031c70cab4e).
