### ISSUE TITLE
how to render images on article pages

### ISSUE THREAD

**Issue by andreantonacci** [tilburgsciencehub/tsh-website#40]
Currently, all images are missing from the articles.
![image](https://user-images.githubusercontent.com/50109671/104177780-9cf9fd80-5409-11eb-97d6-ce5db96fc932.png)

They are located in the same folder where the article lies. For instance, the r.png missing in the screenshot above is located in the same folder of the article itself, r.md

![image](https://user-images.githubusercontent.com/50109671/104177936-dfbbd580-5409-11eb-9bda-f74ed5a60379.png)

We would like to keep this location for the images and avoid placing them in just one img folder at the root. The idea is that every piece of content (a tutorial for example) is self-contained. Everything that is used to render that article is in the same folder, including images.

Could you fix this?

**Comment by heyarviind** [comment]
This works fine, you have to give the exact path of the image. I know (r.png) is the exact path but because Hugo convert the  sub-articles to the child pages, you need to pass the path of one directory above... just like the image shown below

![Screenshot 2021-01-11 at 5 48 28 PM](https://user-images.githubusercontent.com/21043614/104182136-fd9f2f80-5435-11eb-9148-f981d98bdcf6.png)

**Comment by andreantonacci** [comment]
Awesome, thanks!
