### ISSUE TITLE
add admonitions to site

### ISSUE THREAD

**Issue by hannesdatta** [tilburgsciencehub/tsh-website#5]
On our old site, we've been using Admonitions, e.g., tips, warnings.

![image](https://user-images.githubusercontent.com/16557730/103988648-c78c5200-518e-11eb-94fb-9744aec9e753.png)

These rendered as something like this:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/16557730/103988754-ea1e6b00-518e-11eb-870b-c90ec9be2667.png">

Please implement the usage of Hugo Admonitions (warnings, hint, etc.) in our site. The doc from Hugo can be found here.

https://gohugo.io/contribute/documentation/#warning-admonition

I tried using the flags {{ < note > }} as described in the docs, but that renders a server error.

**Comment by heyarviind** [comment]
Yes, I have checked the documentation already, but for me, it works for {{% warning %}} tags but not for "!!!".

It is giving you an error because the site is not yet fully configured for using admonition.

The easy and best use case for this would be to convert !!! to {{% warning %}} and I can create the HTML for that and there would be no server error.

**Comment by hannesdatta** [comment]
You're so fast. 

Thanks.

Please add *three* types of things here: warning, tip, and summary. You can also have some basic background color for each of these blocks. Our designer can then pick a good color for each one of those.

Of course, we can all convert the !!! in our source code - not a prob at all :)

**Comment by heyarviind** [comment]
Sure, I am making changes in the markdown and designing the Admonitions
